Squashed 'osb-dashboard/' changes from efed84b..bfd24cf
bfd24cf Merge branch 'mysql-upstream'
19a22d7 fix(removed-sample-module): MongoDB contained sample module, which is not necessary --> removed
b4c5e45 fix(generalComponente): fixes errors when page is loaded
fef4d24 fix(dashboard): changes service key creation endpoint to an post request
7eb944b feat(core-http): added ability to add additional custom headers from "outside" of a service
820cbf3 fix(empty-object): fixing main.777d60868591dbeafc84.bundle.js:1 ERROR TypeError: Cannot read property 'service_instance_id' of undefined
89214c4 Merge commit 'a6827fae3b790b8919156234eb3e7f11ff25af3f' into feature/backupapi
b2e494f Merge commit '731b04e80b913adc068f92f2e7a4d670fcb33e88' into feature/backupapi
6311619 Merge commit '1e921cc41b4db1b56f3f00aaae57a3e1f9332fb0' into feature/backupapi
be5fe5b Merge commit '2cc3d5d51df59df64a1769d3ded77831aa16d3a2' into feature/backupapi
c8f37ec fix(remove-upgrade): removed yarn upgrade
5671e91 fix(yarn-goal): Yarn upgrade during build process
1948866 Merge commit 'cf7376df9181e121333825574cc3b97e079e6c28' into feature/backupapi
53826f1 feat(mvn): adds yarn update v0.27.5 info Visit https://yarnpkg.com/en/docs/cli/upgrade for documentation about this command. phase to dashboard build
b3f6496 Merge commit 'ea4c728ba4025a4ec5903f52c29ca2b3cc7700f6' into feature/backupapi
8e2eb4f fix(dashboard) fixes build errors

git-subtree-dir: osb-dashboard
git-subtree-split: bfd24cf837ad9a8fa973f8abe38d9bc7452cc712